#!/usr/bin/env node
// Renders src/index.html to output/sekool-explainer.mp4
//
//   node render/render.mjs                 full render (video + audio)
//   node render/render.mjs --stills 3,10   PNG stills at the given seconds -> build/stills/
//   node render/render.mjs --workers 3     parallel browser pages (default: 3)
//   node render/render.mjs --audio-only    only regenerate build/soundtrack.wav
//
// Pipeline: static server -> Chromium (Playwright) seeks the GSAP timeline frame by
// frame -> PNGs piped into ffmpeg (one segment per worker) -> concat -> mux the
// soundtrack generated by audio/generate_audio.py from the SFX cues in the page.
import { chromium } from 'playwright';
import { spawn, execFileSync } from 'node:child_process';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BUILD = path.join(ROOT, 'build');
const OUT = path.join(ROOT, 'output');
fs.mkdirSync(BUILD, { recursive: true });
fs.mkdirSync(OUT, { recursive: true });

const args = process.argv.slice(2);
const opt = (name, def) => { const i = args.indexOf(`--${name}`); return i >= 0 ? args[i + 1] : def; };
const STILLS = opt('stills', null);
const WORKERS = +opt('workers', 3);
const AUDIO_ONLY = args.includes('--audio-only');
const FFMPEG = process.env.FFMPEG || execFileSync('python3', ['-c', 'import imageio_ffmpeg as f; print(f.get_ffmpeg_exe())']).toString().trim();

const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.woff2': 'font/woff2', '.woff': 'font/woff',
  '.png': 'image/png', '.jpg': 'image/jpeg', '.svg': 'image/svg+xml', '.wav': 'audio/wav', '.json': 'application/json' };
const server = http.createServer((req, res) => {
  const p = path.join(ROOT, decodeURIComponent(new URL(req.url, 'http://x').pathname));
  if (!p.startsWith(ROOT) || !fs.existsSync(p) || fs.statSync(p).isDirectory()) { res.writeHead(404); return res.end(); }
  res.writeHead(200, { 'content-type': MIME[path.extname(p)] || 'application/octet-stream' });
  fs.createReadStream(p).pipe(res);
});
await new Promise((r) => server.listen(0, '127.0.0.1', r));
const URL_ = `http://127.0.0.1:${server.address().port}/src/index.html?render`;

const browser = await chromium.launch();
async function openPage() {
  const page = await browser.newPage({ viewport: { width: 1920, height: 1080 }, deviceScaleFactor: 1 });
  page.on('pageerror', (e) => console.error('page error:', e.message));
  page.on('console', (m) => m.type() === 'error' && !m.text().includes('404') && console.error('console:', m.text()));
  await page.goto(URL_);
  await page.evaluate(() => window.SEKOOL.ready);
  return page;
}
const snap = async (page, t, type = 'png') => {
  await page.evaluate((t) => window.SEKOOL.seek(t), t);
  return page.screenshot({ type, ...(type === 'jpeg' ? { quality: 95 } : {}), clip: { x: 0, y: 0, width: 1920, height: 1080 } });
};

const run = (cmd, a) => new Promise((res, rej) => {
  const p = spawn(cmd, a, { stdio: ['ignore', 'inherit', 'inherit'] });
  p.on('exit', (c) => (c === 0 ? res() : rej(new Error(`${cmd} exited ${c}`))));
});

try {
  const first = await openPage();
  const { duration, fps, cues, music } = await first.evaluate(() => ({
    duration: window.SEKOOL.duration, fps: window.SEKOOL.fps, cues: window.SEKOOL.cues, music: window.SEKOOL.music,
  }));

  if (STILLS) {
    const dir = path.join(BUILD, 'stills');
    fs.mkdirSync(dir, { recursive: true });
    for (const s of STILLS.split(',').map(Number)) {
      const f = path.join(dir, `t${s.toFixed(2).padStart(6, '0')}.png`);
      fs.writeFileSync(f, await snap(first, s));
      console.log('still', f);
    }
  } else {
    // 1) audio
    fs.writeFileSync(path.join(BUILD, 'cues.json'), JSON.stringify({ duration, music, cues }, null, 2));
    await run('python3', [path.join(ROOT, 'audio/generate_audio.py'), path.join(BUILD, 'cues.json'), path.join(BUILD, 'soundtrack.wav')]);
    if (AUDIO_ONLY) process.exit(0);

    // 2) video segments in parallel
    const total = Math.round(duration * fps);
    const per = Math.ceil(total / WORKERS);
    const started = Date.now();
    let done = 0;
    const pages = [first, ...(await Promise.all(Array.from({ length: WORKERS - 1 }, openPage)))];
    const segs = await Promise.all(pages.map(async (page, w) => {
      const a = w * per, b = Math.min(total, a + per);
      const file = path.join(BUILD, `seg${w}.mp4`);
      const ff = spawn(FFMPEG, ['-y', '-loglevel', 'error', '-f', 'image2pipe', '-framerate', String(fps), '-c:v', 'mjpeg', '-i', '-',
        '-c:v', 'libx264', '-preset', 'medium', '-tune', 'animation', '-crf', '16', '-pix_fmt', 'yuv420p', '-r', String(fps), file],
      { stdio: ['pipe', 'inherit', 'inherit'] });
      const closed = new Promise((res, rej) => ff.on('exit', (c) => (c === 0 ? res() : rej(new Error('ffmpeg segment failed')))));
      // seek in order from 0 so every tween records its start values the same way
      await page.evaluate(() => window.SEKOOL.seek(0));
      for (let f = a; f < b; f++) {
        const buf = await snap(page, f / fps, 'jpeg');
        if (!ff.stdin.write(buf)) await new Promise((r) => ff.stdin.once('drain', r));
        if (++done % 150 === 0) console.log(`frames ${done}/${total}  (${((Date.now() - started) / 1000).toFixed(0)}s)`);
      }
      ff.stdin.end();
      await closed;
      return file;
    }));

    // 3) concat + mux + loudness normalise
    const list = path.join(BUILD, 'segments.txt');
    fs.writeFileSync(list, segs.map((s) => `file '${s}'`).join('\n'));
    const out = path.join(OUT, 'sekool-explainer.mp4');
    await run(FFMPEG, ['-y', '-loglevel', 'error', '-f', 'concat', '-safe', '0', '-i', list, '-i', path.join(BUILD, 'soundtrack.wav'),
      '-map', '0:v', '-map', '1:a', '-c:v', 'copy', '-af', 'loudnorm=I=-16:TP=-1.5:LRA=11', '-c:a', 'aac', '-b:a', '192k', '-ar', '48000',
      '-t', String(duration), '-movflags', '+faststart', out]);
    console.log(`done: ${out}  (${((Date.now() - started) / 1000).toFixed(0)}s)`);
  }
} finally {
  await browser.close();
  server.close();
}
